name: Firebase IaC

on:
  push:
    branches: [ main ]
    paths: [ 'flutter-payroll-scanner/terraform/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'flutter-payroll-scanner/terraform/**' ]

env:
  TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
  TF_VAR_region: "europe-west2"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

    - uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      working-directory: ./flutter-payroll-scanner/terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./flutter-payroll-scanner/terraform

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      working-directory: ./flutter-payroll-scanner/terraform
